### ISSUE TITLE
does not support the capabilities interaction.

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/gp-connect-prescriptions-management-fhir#32]
> •	…it does not support the capabilities interaction.
> Is there a good reason for not doing so?

- Comment from Tim Coates

**Comment by agreenhalgh** [comment]
Possibly a suggestion from Mick S as consistent with PDS spec. @edtu1 to confirm on email.

**Comment by edtu1** [comment]
Mick S emailed

**Comment by edtu1** [comment]
From Mick: I think we discovered that we'd missed out on complying with this part of the FHIR standard across the board at a late stage and had to retrospectively insert this phrase across all our FHIR API specs.
