### ISSUE TITLE
Endpoints not logically sequenced

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/gp-connect-prescriptions-management-fhir#33]
> •	Endpoints
> It would be good to have the endpoints / interactions in a logical sequence, PATCH comes first but we’re PATCHing something we haven’t seen yet.

- Comment from Tim Coates

**Comment by agreenhalgh** [comment]
We may be able to just reorder 
```
x-spec-publication:
  operation-order:
```

There are display guidelines in API-M producer zone - align with these.

**Comment by edtu1** [comment]
Will add grouping to endpoints.

**Comment by edtu1** [comment]
hopefully covered in latest commit #64
