### ISSUE TITLE
Seperate MedicationStatement endpoint

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/gp-connect-prescriptions-management-fhir#38]
> •	In GET /FHIR/R4/MedicationStatement
> It looks like this is a search endpoint, but the example response shown suggests it’s a single item Read rather than search?
> Happy for either to be provided / supported but suggest separating them out in the OAS spec?
- Comment from Tim Coates

**Comment by edtu1** [comment]
Covered by #45
