### ISSUE TITLE
Formatting of MedicationRequest.authoredon search param

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/gp-connect-prescriptions-management-fhir#57]
Parameter definition has 
```
- in: query
          name: authoredon
```
but example has:
`To use a range use authored-on=geYYYY-MM-DD&authored-on=leYYYY-MM-DD`

**Comment by agreenhalgh** [comment]
Example object has
```
authoredOn: 2022-10-13T16:20:27+07:00
```

**Comment by edtu1** [comment]
I think this is still valid, EPS uses it and according to docs its how to search: https://www.hl7.org/fhir/search.html#date wouldn't want to strip the authored on date to not have time.
