### ISSUE TITLE
Need to remove Session URID for patietn facing services as isn't relevant for NHS Login

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/gp-connect-prescriptions-management-fhir#66]
Remove the URID parameter completely as this isn't relevant for patient login

https://github.com/NHSDigital/gp-connect-prescriptions-management-fhir/blob/8f016d612114d65fdfe78d677f940f40aa2289dd/specification/gp-connect-prescriptions-management-fhir.yaml#L1067

**Comment by edtu1** [comment]
Removed, wasn't used in the endpoints but schema was present.
