### ISSUE TITLE
EPS Rx ID should be in groupIdentifier

### ISSUE THREAD

**Issue by agreenhalgh** [NHSDigital/gp-connect-prescriptions-management-fhir#76]
The existing GPC model requires that EPS ID is in groupIdentifier

> The EPS prescriptionID if this medication or medical device has been prescribed via the Electronic Prescriptions Service. The element in the Identifier data type that MUST be populated when a groupIdentifier is populated is identifier.value.

> All EPS prescribed drugs MUST have the prescriptionID present in this field and have system element set to https://fhir.nhs.uk/Id/prescription-order-number.

https://developer.nhs.uk/apis/gpconnect-1-6-0/accessrecord_structured_development_medicationrequest.html#groupidentifier

We are storing in medicationrequest.identifier - it should be in both of these elements

> If the EPS identifier is present then the identifier.value is where the EPS Id SHOULD also be added. The codeSystem for this identifier is https://fhir.nhs.uk/Id/prescription-order-item-number

**Comment by agreenhalgh** [comment]
I have this slightly wrong - the groupIdentifier is the _prescription_ ID, the medicationResuest.identifier is the _EPS line item_ ID

**Comment by agreenhalgh** [comment]
line item is just a UUID, EPS Rx ID is the EPS specific format

**Comment by edtu1** [comment]
Updated, just needs to be reflected in simplifier.
